// Deterministic WebdriverIO + Cucumber codegen from gate decisions. The
// feature files stay the executable spec; this emits their step definitions
// and a Sauce Labs config per platform.
import path from 'node:path';
import type { Platform, PlatformResult, ResolvedLocator, StepDecision, StepKind } from './types.mts';

// RN maps testID to accessibilityIdentifier on iOS and to the view's
// resource-id on Android; accessibilityLabel is the accessibility id on iOS
// and content-desc on Android, which `~` covers on both. The Android testID
// mapping is the one to confirm in the live-validation pass.
export function selector(platform: Platform, loc: ResolvedLocator): string {
  if (loc.attribute === 'testID' && platform === 'android') {
    return `android=new UiSelector().resourceId(${JSON.stringify(loc.id)})`;
  }
  return `~${loc.id}`;
}

const KEYWORD: Record<StepKind, string> = { context: 'Given', action: 'When', outcome: 'Then' };

function stepPattern(text: string): string {
  // Regex rather than a Cucumber Expression: step text may contain {, (, or /
  // which Cucumber Expressions would treat as syntax.
  return `/^${text.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}$/`;
}

function body(platform: Platform, d: StepDecision): string[] {
  if (d.verdict !== 'accepted') {
    const why =
      d.verdict === 'ungrounded'
        ? [`UNGROUNDED: ${d.proposal.rationale}`, ...(d.proposal.gap ? [`testability gap at ${d.proposal.gap}`] : ['no source evidence'])]
        : ['REJECTED by the grounding gate:', ...d.errors.map((e) => `${e.rule} ${e.message}`)];
    return [...why.map((l) => `// ${l}`), `return 'pending';`];
  }
  const p = d.proposal;
  if (p.action === 'back') return [`// proposed by ${p.source === 'rules' ? 'rule match' : 'Copilot agent'}`, 'await driver.back();'];

  const loc = d.locator!;
  const sel = JSON.stringify(selector(platform, loc));
  const notes = [
    `// ${loc.attribute}=${loc.id} (${loc.evidence}), proposed by ${p.source === 'rules' ? 'rule match' : 'Copilot agent'}`,
    ...(loc.conditions.length ? [`// renders only when ${loc.conditions.join(' && ')}`] : []),
    ...d.warnings.map((w) => `// WARNING ${w.rule}: ${w.message}`),
  ];
  const action = {
    tap: `await $(${sel}).click();`,
    type: `await $(${sel}).setValue(${JSON.stringify(p.text)});`,
    assertVisible: `await expect($(${sel})).toBeDisplayed();`,
    assertNotVisible: `await expect($(${sel})).not.toBeDisplayed();`,
  }[p.action as 'tap' | 'type' | 'assertVisible' | 'assertNotVisible'];
  return [...notes, action];
}

export function generateSteps(result: PlatformResult): string {
  // A step's keyword comes from its first use; Cucumber matches definitions
  // regardless of keyword, so this only affects readability.
  const kinds = new Map<string, StepKind>();
  for (const s of result.feature.scenarios.flatMap((sc) => sc.steps)) {
    if (!kinds.has(s.text)) kinds.set(s.text, s.kind);
  }

  const out = [
    `// GENERATED by generator/cli.mts from ${result.feature.file}. Do not edit;`,
    `// fix the feature, test data, or app testIDs and regenerate.`,
    `import { Given, When, Then } from '@wdio/cucumber-framework';`,
    `import { $, driver, expect } from '@wdio/globals';`,
    '',
  ];
  for (const d of result.steps) {
    out.push(`${KEYWORD[kinds.get(d.step) ?? 'action']}(${stepPattern(d.step)}, async () => {`);
    out.push(...body(result.platform, d).map((l) => `  ${l}`));
    out.push('});', '');
  }
  return out.join('\n');
}

const CAPABILITIES: Record<Platform, Record<string, unknown>> = {
  android: {
    platformName: 'Android',
    'appium:automationName': 'UiAutomator2',
    'appium:deviceName': 'Google Pixel.*',
  },
  ios: {
    platformName: 'iOS',
    'appium:automationName': 'XCUITest',
    'appium:deviceName': 'iPhone.*',
  },
};

export function generateConfig(story: string, platform: Platform, featureFile: string, outDir: string): string {
  const spec = path.relative(outDir, featureFile);
  const caps = Object.entries(CAPABILITIES[platform])
    .map(([k, v]) => `      '${k}': '${v}',`)
    .join('\n');
  const appEnv = `SAUCE_APP_${platform.toUpperCase()}`;
  return `// GENERATED by generator/cli.mts. Sauce Labs run for ${story} on ${platform}.
// Needs SAUCE_USERNAME, SAUCE_ACCESS_KEY, and ${appEnv} (e.g. storage:filename=app.${platform === 'ios' ? 'ipa' : 'apk'}).
export const config: WebdriverIO.Config = {
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  region: (process.env.SAUCE_REGION as 'us' | 'eu' | undefined) ?? 'us',
  services: ['sauce'],
  specs: ['${spec}'],
  framework: 'cucumber',
  cucumberOpts: {
    require: ['./${platform}/steps.ts'],
    timeout: 120000,
  },
  reporters: ['spec'],
  maxInstances: 1,
  capabilities: [
    {
${caps}
      'appium:app': process.env.${appEnv},
      'sauce:options': {
        appiumVersion: 'latest',
        build: process.env.SAUCE_BUILD ?? '${story}',
        name: '${story} ${platform}',
      },
    },
  ],
};
`;
}
