// Deterministic WebdriverIO + Cucumber codegen from gate decisions. The
// feature files stay the executable spec; this emits their step definitions
// and a Sauce Labs config per platform.
import path from 'node:path';
import type { Platform, PlatformResult, ResolvedLocator, StepDecision, StepKind } from './types.mts';

// RN maps testID to accessibilityIdentifier on iOS and to the view's
// resource-id on Android; accessibilityLabel is the accessibility id on iOS
// and content-desc on Android, which `~` covers on both. The Android testID
// mapping is the one to confirm in the live-validation pass.
export function selector(platform: Platform, loc: ResolvedLocator): string {
  if (loc.attribute === 'testID' && platform === 'android') {
    return `android=new UiSelector().resourceId(${JSON.stringify(loc.id)})`;
  }
  return `~${loc.id}`;
}

const KEYWORD: Record<StepKind, string> = { context: 'Given', action: 'When', outcome: 'Then' };

function stepPattern(text: string): string {
  // Regex rather than a Cucumber Expression: step text may contain {, (, or /
  // which Cucumber Expressions would treat as syntax.
  return `/^${text.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&')}$/`;
}

function body(platform: Platform, d: StepDecision): string[] {
  if (d.verdict !== 'accepted') {
    const why =
      d.verdict === 'ungrounded'
        ? [`UNGROUNDED: ${d.proposal.rationale}`, ...(d.proposal.gap ? [`testability gap at ${d.proposal.gap}`] : ['no source evidence'])]
        : ['REJECTED by the grounding gate:', ...d.errors.map((e) => `${e.rule} ${e.message}`)];
    return [...why.map((l) => `// ${l}`), `return 'pending';`];
  }
  const p = d.proposal;
  if (p.action === 'back') return [`// proposed by ${p.source === 'rules' ? 'rule match' : 'Copilot agent'}`, 'await driver.back();'];

  const loc = d.locator!;
  const sel = JSON.stringify(selector(platform, loc));
  const notes = [
    `// ${loc.attribute}=${loc.id} (${loc.evidence}), proposed by ${p.source === 'rules' ? 'rule match' : 'Copilot agent'}`,
    ...(loc.conditions.length ? [`// renders only when ${loc.conditions.join(' && ')}`] : []),
    ...d.warnings.map((w) => `// WARNING ${w.rule}: ${w.message}`),
  ];
  // XCUITest reports RN container views (a View wrapping other elements) as
  // visible="false" even while their screen is on top, so a displayed check
  // on one always fails on iOS. Found in the first live iOS run; for those,
  // presence in the tree is the signal that the screen rendered.
  const containerOnIos = platform === 'ios' && /View$/.test(loc.element);
  const shown = containerOnIos ? 'toBeExisting()' : 'toBeDisplayed()';
  const action = {
    tap: `await $(${sel}).click();`,
    type: `await $(${sel}).setValue(${JSON.stringify(p.text)});`,
    assertVisible: `await expect($(${sel})).${shown};`,
    assertNotVisible: `await expect($(${sel})).not.${shown};`,
  }[p.action as 'tap' | 'type' | 'assertVisible' | 'assertNotVisible'];
  return [...notes, ...(containerOnIos && p.action.startsWith('assert') ? ['// iOS container view: asserts presence, see codegen.mts'] : []), action];
}

export function generateSteps(result: PlatformResult): string {
  // A step's keyword comes from its first use; Cucumber matches definitions
  // regardless of keyword, so this only affects readability.
  const kinds = new Map<string, StepKind>();
  for (const s of result.feature.scenarios.flatMap((sc) => sc.steps)) {
    if (!kinds.has(s.text)) kinds.set(s.text, s.kind);
  }

  const out = [
    `// GENERATED by generator/cli.mts from ${result.feature.file}. Do not edit;`,
    `// fix the feature, test data, or app testIDs and regenerate.`,
    `import { Given, When, Then } from '@wdio/cucumber-framework';`,
    `import { $, driver, expect } from '@wdio/globals';`,
    '',
  ];
  for (const d of result.steps) {
    out.push(`${KEYWORD[kinds.get(d.step) ?? 'action']}(${stepPattern(d.step)}, async () => {`);
    out.push(...body(result.platform, d).map((l) => `  ${l}`));
    out.push('});', '');
  }
  return out.join('\n');
}

export type RunTarget = 'sauce' | 'local';

const DEVICE: Record<RunTarget, Record<Platform, Record<string, string | number>>> = {
  sauce: {
    android: { platformName: 'Android', 'appium:automationName': 'UiAutomator2', 'appium:deviceName': 'Google Pixel.*' },
    ios: { platformName: 'iOS', 'appium:automationName': 'XCUITest', 'appium:deviceName': 'iPhone.*' },
  },
  local: {
    // A local emulator sharing a laptop with builds can take longer than
    // Appium's 20s default for routine adb commands (pm clear timed out).
    android: {
      platformName: 'Android',
      'appium:automationName': 'UiAutomator2',
      'appium:deviceName': 'Android Emulator',
      'appium:adbExecTimeout': 60000,
    },
    // WebDriverAgent is built and launched on the simulator on first use,
    // which outlasts Appium's default wait on a busy machine.
    ios: {
      platformName: 'iOS',
      'appium:automationName': 'XCUITest',
      'appium:deviceName': 'iPhone 17',
      'appium:wdaLaunchTimeout': 240000,
      'appium:wdaConnectionTimeout': 240000,
    },
  },
};

// The app binary each target installs. Local builds come from
// `npx expo run:*` / Gradle; override with APP_ANDROID / APP_IOS.
const LOCAL_APP: Record<Platform, string> = {
  android: 'android/app/build/outputs/apk/release/app-release.apk',
  ios: 'ios/build/Build/Products/Release-iphonesimulator/rngroundingtest.app',
};

export function generateConfig(
  story: string,
  platform: Platform,
  featureFile: string,
  outDir: string,
  target: RunTarget,
  appId: string,
): string {
  const spec = path.relative(outDir, featureFile);
  const caps = Object.entries(DEVICE[target][platform])
    .map(([k, v]) => `      '${k}': ${typeof v === 'number' ? v : `'${v}'`},`)
    .join('\n');
  const appEnv = target === 'sauce' ? `SAUCE_APP_${platform.toUpperCase()}` : `APP_${platform.toUpperCase()}`;
  const header =
    target === 'sauce'
      ? `// GENERATED by generator/cli.mts. Sauce Labs run for ${story} on ${platform}.
// Needs SAUCE_USERNAME, SAUCE_ACCESS_KEY, and ${appEnv} (e.g. storage:filename=app.${platform === 'ios' ? 'ipa' : 'apk'}).`
      : `// GENERATED by generator/cli.mts. Local run for ${story} on ${platform}: starts Appium itself
// and installs the local build (override with ${appEnv}) on a running ${platform === 'ios' ? 'simulator' : 'emulator'}.`;
  const connection =
    target === 'sauce'
      ? `  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  region: (process.env.SAUCE_REGION as 'us' | 'eu' | undefined) ?? 'us',
  services: ['sauce'],`
      : `  port: 4723,
  services: ['appium'],`;
  const app =
    target === 'sauce'
      ? `process.env.${appEnv}`
      : `process.env.${appEnv} ?? path.resolve(__dirname, ${JSON.stringify(path.relative(outDir, path.join(path.dirname(featureFile), '../..', LOCAL_APP[platform])))})`;
  const vendor =
    target === 'sauce'
      ? `
      'sauce:options': {
        appiumVersion: 'latest',
        build: process.env.SAUCE_BUILD ?? '${story}',
        name: '${story} ${platform}',
      },`
      : '';
  return `${header}
import path from 'node:path';

export const config: WebdriverIO.Config = {
${connection}
  specs: ['${spec}'],
  framework: 'cucumber',
  cucumberOpts: {
    // Cucumber resolves these from the working directory, not this file.
    require: [path.resolve(__dirname, '${platform}/steps.ts')],
    timeout: 120000,
  },
  reporters: ['spec'],
  maxInstances: 1,
  // Assertions and element lookups wait up to this long. The 5s default
  // failed a screen transition on a freshly booted emulator.
  waitforTimeout: 15000,
  capabilities: [
    {
${caps}
      'appium:app': ${app},${vendor}
    },
  ],
  // Every scenario starts from a cold launch (the login screen); the app
  // keeps its signed-in session in memory, so a restart is a clean slate.
  beforeScenario: async () => {
    await driver.terminateApp('${appId}');
    await driver.activateApp('${appId}');
  },
};
`;
}
