// Deterministic WebdriverIO page objects, one per screen, generated from the
// whole app's registry and shared by every story's step definitions. Locators
// live only here; steps reference page members, so a changed testID is one
// regenerated line rather than an edit in every step that uses it.
import path from 'node:path';
import { evaluateExpression } from './conditions.mts';
import { evidence } from './registry.mts';
import type { RegistryFinding } from './types.mts';

export interface PageMember {
  page: string; // class name, e.g. LoginPage
  file: string; // e.g. login.page
  name: string; // getter or method name
  params: string[]; // empty for a getter
  paramSources: string[]; // template expressions feeding each param, e.g. item.id
  container: boolean; // an RN View wrapping other elements
  finding: RegistryFinding;
}

export interface PageModel {
  pages: Map<string, { cls: string; file: string; screen: string; members: PageMember[]; gaps: RegistryFinding[] }>;
  byValue: Map<string, PageMember>;
}

const words = (s: string) => s.split(/[^A-Za-z0-9]+|(?<=[a-z0-9])(?=[A-Z])/).filter(Boolean).map((w) => w.toLowerCase());
const camel = (ws: string[]) => ws.map((w, i) => (i ? w[0].toUpperCase() + w.slice(1) : w)).join('');
const pascal = (ws: string[]) => ws.map((w) => w[0].toUpperCase() + w.slice(1)).join('');
const TEMPLATE = /^\{`(.*)`\}$/s;

function screenWords(screen: string): string[] {
  const ws = words(screen);
  return ws[ws.length - 1] === 'screen' ? ws.slice(0, -1) : ws;
}

// A member is named from its testID. The screen's own words are dropped when
// the ID starts with all of them (login-submit-button on Login -> submitButton);
// a screen's root container is `root`.
function memberName(f: RegistryFinding, screen: string[]): string {
  const raw = (f.value ?? '').replace(TEMPLATE, '$1').replace(/\$\{[^}]*\}/g, ' ');
  let ws = words(raw);
  const prefixed = screen.length < ws.length && screen.every((w, i) => ws[i] === w);
  if (prefixed) ws = ws.slice(screen.length);
  if (/View$/.test(f.element) && ws[ws.length - 1] === 'screen') return 'root';
  const name = camel(ws.length ? ws : ['element']);
  return /^[0-9]/.test(name) ? `_${name}` : name;
}

export function buildPageModel(registry: RegistryFinding[]): PageModel {
  const pages: PageModel['pages'] = new Map();
  const byValue = new Map<string, PageMember>();

  for (const f of registry) {
    let page = pages.get(f.screen);
    if (!page) {
      const sw = screenWords(f.screen);
      page = { cls: `${pascal(sw)}Page`, file: `${sw.join('-')}.page`, screen: f.screen, members: [], gaps: [] };
      pages.set(f.screen, page);
    }
    if (f.category === 'missing') {
      page.gaps.push(f);
      continue;
    }
    // Expression IDs cannot be written as a selector; the gate rejects them too.
    if (f.category === 'expression-dynamic' || !f.value || byValue.has(f.value)) continue;

    const paramSources = [...(f.value.match(TEMPLATE)?.[1] ?? '').matchAll(/\$\{([^}]+)\}/g)].map((m) => m[1].trim());
    const params = paramSources.map((src, i) => {
      const last = words(src).pop() ?? 'value';
      return paramSources.slice(0, i).some((s) => words(s).pop() === last) ? `${last}${i + 1}` : last;
    });
    let name = memberName(f, screenWords(f.screen));
    const taken = new Set(page.members.map((m) => m.name));
    for (let n = 2; taken.has(name); n++) name = `${memberName(f, screenWords(f.screen))}${n}`;

    const member: PageMember = {
      page: page.cls,
      file: page.file,
      name,
      params,
      paramSources,
      container: /View$/.test(f.element),
      finding: f,
    };
    page.members.push(member);
    byValue.set(f.value, member);
  }
  return { pages, byValue };
}

// The call expression a step uses, with template params filled from the
// test-data record the gate already validated.
export function memberCall(m: PageMember, record: Record<string, unknown> | undefined): string {
  if (!m.params.length) return `${m.page}.${m.name}`;
  const args = m.paramSources.map((src) => JSON.stringify(String(evaluateExpression(src, { item: record }))));
  return `${m.page}.${m.name}(${args.join(', ')})`;
}

export function importPath(fromDir: string, pageObjectsDir: string, file: string): string {
  const rel = path.relative(fromDir, path.join(pageObjectsDir, file)).split(path.sep).join('/');
  return rel.startsWith('.') ? rel : `./${rel}`;
}

export const BASE_PAGE = `// GENERATED by generator/cli.mts. Base for every page object: the one place
// that knows how React Native locators surface on each platform.
import { $, driver, expect } from '@wdio/globals';

export default class Page {
  // RN sets testID as the view's resource-id on Android and as its
  // accessibilityIdentifier on iOS (verified on an Android 36 emulator and
  // the iOS 27 simulator).
  protected byTestId(id: string) {
    return $(driver.isAndroid ? \`android=new UiSelector().resourceId("\${id}")\` : \`~\${id}\`);
  }

  // accessibilityLabel: content-desc on Android, the accessibility id on iOS.
  protected byLabel(label: string) {
    return $(\`~\${label}\`);
  }
}

type Element = ReturnType<typeof $>;

// XCUITest reports RN container views as visible="false" even while their
// screen is on top, so on iOS a container is asserted by presence instead.
export async function expectShown(el: Element, opts: { container?: boolean } = {}) {
  if (opts.container && driver.isIOS) await expect(el).toBeExisting();
  else await expect(el).toBeDisplayed();
}

export async function expectHidden(el: Element, opts: { container?: boolean } = {}) {
  if (opts.container && driver.isIOS) await expect(el).not.toBeExisting();
  else await expect(el).not.toBeDisplayed();
}

// Typing into RN inputs over XCUITest intermittently lost the first
// characters (the keyboard was still coming up) and occasionally reordered
// them, which signed in the wrong persona. Focus first, wait for the
// keyboard, then read the field back and retype on a mismatch. Secure fields
// read back as bullets, so a bullet string of the right length counts.
export async function typeText(el: Element, text: string) {
  let got = '';
  for (let attempt = 1; attempt <= 3; attempt++) {
    await el.click();
    await driver.waitUntil(() => driver.isKeyboardShown(), { timeout: 5000 }).catch(() => undefined);
    await el.clearValue();
    await el.setValue(text);
    got = await el.getText();
    if (got === text || (got.length === text.length && /^[•●]+$/.test(got))) return;
  }
  throw new Error(\`typed "\${text}" but the field shows "\${got}" after 3 attempts\`);
}
`;

export function renderPage(page: PageModel['pages'] extends Map<string, infer P> ? P : never): string {
  const out = [
    `// GENERATED by generator/cli.mts from ${page.screen}. Do not edit; change the`,
    `// app's testIDs and regenerate.`,
    `import Page from './base.page';`,
    '',
  ];
  if (page.gaps.length) {
    out.push('// Testability gaps (interactive elements with no locator, not reachable here):');
    for (const g of page.gaps) out.push(`//   ${g.element}${g.description ? ` "${g.description}"` : ''} at ${evidence(g)}`);
    out.push('');
  }
  out.push(`class ${page.cls} extends Page {`);
  page.members.forEach((m, i) => {
    const f = m.finding;
    const notes = [
      `${f.attribute}=${f.value} (${evidence(f)})`,
      ...(f.conditions.length ? [`renders only when ${f.conditions.join(' && ')}`] : []),
      ...(f.locatorStrength !== 'strong' ? [`WARNING: ${f.attribute} only; ask for a testID`] : []),
    ];
    const by = f.attribute === 'testID' ? 'byTestId' : 'byLabel';
    let n = 0;
    const arg = m.params.length
      ? `\`${(f.value as string).replace(TEMPLATE, '$1').replace(/\$\{[^}]+\}/g, () => `\${${m.params[n++]}}`)}\``
      : JSON.stringify(f.value);
    if (i) out.push('');
    out.push(...notes.map((n) => `  // ${n}`));
    out.push(
      m.params.length
        ? `  ${m.name}(${m.params.map((p) => `${p}: string`).join(', ')}) {\n    return this.${by}(${arg});\n  }`
        : `  get ${m.name}() {\n    return this.${by}(${arg});\n  }`,
    );
  });
  out.push('}', '', `export default new ${page.cls}();`, '');
  return out.join('\n');
}
